---
title: "ILINet + Weather Colorado Regression Model"
output: html_notebook
---
```{r}
library(tidyverse)
library(ggplot2)
library(scales)
library(lubridate)
library(caret)
library(Matrix)
```
# Data Loading ----

```{r}
colorado_weather <- read_csv('input/Colorado-Station-Report.csv') %>% 
  select(-STATION, -NAME)

ilinet_colorado <- readRDS('data/train.rds') %>% 
  filter(REGION == 'Colorado')
```
# Time series visualization ----

```{r}
colorado_weather %>% 
  select(-DATE) %>% 
  mutate_all(
    funs(rescale, "rescale", rescale(., to = c(0, 1)))
  ) %>% 
  select(contains('rescale')) %>% 
  ts.plot(col = c('blue', 'red', 'green'))
```

```{r}
colorado_weather
```


```{r}
ilinet_colorado %>% 
  select(-REGION, -YEAR, -WEEK, -YEARWEEK, -PRETTYDATE) %>% 
  mutate_all(
    funs(rescale, "rescale", rescale(., to = c(0, 1)))
  ) %>% 
  select(contains('rescale')) %>% 
  ts.plot(col = c('blue', 'red', 'green', 'black'))
```
```{r}
ilinet_colorado
```


# Preprocessing ----

```{r}
train <- ilinet_colorado %>% 
  mutate(
    MONTH = lubridate::month(PRETTYDATE)
  ) %>% 
  left_join(
    colorado_weather %>% 
      rowwise() %>% 
      mutate(
        YEAR  = as.integer(str_split(DATE, pattern = '-', simplify = TRUE)[1]),
        MONTH = as.integer(str_split(DATE, pattern = '-', simplify = TRUE)[2])
      ) %>% 
      select(-DATE), 
    by = c("YEAR", "MONTH")
  ) %>% 
  mutate(
    RESPONSE = lead(ILITOTAL, n = 1)
  ) %>%
  select(ILITOTAL, PRCP, SNOW, TAVG, RESPONSE)
```
# Train / Test ----

```{r}
test  <- train[391:397, ]
train <- train[1:390, ]
```
# Regression Model ----

```{r}
model <- glm(RESPONSE ~ ., data = train)
```

```{r}
model
```

# Predictions ----

```{r}
prediction <- as.integer(predict(model, newdata = test[, 1:5]))
```


```{r}
# Metrics ----
RMSE(prediction, test$RESPONSE, na.rm = TRUE)
print(prediction)
print(test$RESPONSE)
```

# Regression Model ----
```{r}
h2o.init()
```

```{r}
y <- "RESPONSE"
x <- setdiff(names(train), y)
h2oFrameTraining=as.h2o(train)
aml <- h2o.automl(x = x, y = y,
                  training_frame = h2oFrameTraining,
                  max_runtime_secs = 3600)

```
# Predictions ----

```{r}
lb <- aml@leaderboard
lb
```



```{r}
library(xgboost)
```

```{r}
dtrain <- xgb.DMatrix(data = data.matrix(train), label= train$RESPONSE)
dtest <- xgb.DMatrix(data = data.matrix(test), label= test$RESPONSE)
```


```{r}
modelXg <- xgboost(data = dtrain, # the data   
                 max.depth = 3, # the maximum depth of each decision tree
                 nround = 10, # number of boosting rounds
                 early_stopping_rounds = 3, # if we dont see an improvement in this many rounds, stop
                 objective = "reg:linear", # the objective function
                 gamma = 1) # add a regularization term

```

```{r}
pred <- predict(modelXg, dtest)
RMSE(pred, test$RESPONSE, na.rm = TRUE)
print(pred)
print(test$RESPONSE)
```

